#+TITLE: BlueConduit Experimental Working Group

* Info

| organizer | Ivy Bennett-Ford                        |
| audience  | Product, Engineering, Data Science      |
| cadence   | Every thrird Tuesday                    |
| duration  | One hour                                |

* Purpose

This working group is established with the intent to explore new ideas, audit existing research, and synthesize concepts aligned with BlueConduit's mission. 
BlueConduit determined core values, and published them [[https://docs.google.com/document/d/1_-sdO-DX-pkqueuNntJvKYM7VHnb0wnmsuYpdcKd5Jc/edit][internally]]. 
To uphold these values, members of the BlueConduit team and affiliated community partners are invited to participate in an exploratory reading group. 
From this literature review, generated ideas will be presented to the Product team for future development. 

* Structure
    1. An invitation will be left standing on all BlueConduit calendars.
    2. Suggested materials and structure document will be supplied one week in advance.
    3. Structure(s):
        A. Assigned paper(s) 
        B. Read-along as a group
        C. Participant-selected paper
Though participation is key, it can look different from person to person. Try to read as much as you can, focusing on the abstract and methods. The goal here is to make connections and learn new things related to our work at BlueConduit.

** Research source

Suggested papers will be cached [[file:meta/research-hub/publications.org][here]].
While bringing along papers the reader feels excited about, it would be helpful to document the contact information of authors, so that we can contact them at some point to discuss their work.

* Rights and Responsibilities of the Readers

- The reader has the right to freely voice to the group whatever ideas might occur to them in the course of study
- The reader is responsible for offering critique aligned with BlueConduit's [[https://docs.google.com/document/d/1_-sdO-DX-pkqueuNntJvKYM7VHnb0wnmsuYpdcKd5Jc/edit][values]]
- The reader has the right to challenge another member's ideas during discussion
